name: AntiCheatAutoBan
version: '${project.version}'
main: com.example.anticheatautoban.AntiCheatAutoBan
api-version: '1.21'
description: Paper 1.21.4 anti-cheat — fly, speed, freecam, XRay + Discord logging.
authors: [ AntiCheatAutoBan ]

permissions:
  anticheat.bypass:
    description: Bypasses all anti-cheat checks.
    default: op
  anticheat.alerts:
    description: Receives in-game XRay and cheat alerts.
    default: op
